name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          # Clones rasos devem ser desabilitados para melhor relevância da análise
          fetch-depth: 0 
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build and analyze
        env:
          # O token do SonarCloud que você configurou no GitHub Secrets
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          # O token do GitHub é necessário para decoração de Pull Requests (se aplicável)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Linha 34 deve ser o 'run: |' ou o comando 'mvn'
        run: | 
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=taynarasilveira_ProjetoSimples \
            -Dsonar.organization=taynarasilveira \
            -Dsonar.host.url=https://sonarcloud.io
